### ISSUE TITLE
Refresh infield labels after form reset

### ISSUE THREAD

**Issue by webaholik** [dcneiner/In-Field-Labels-jQuery-Plugin#54]
In your form enter text into input field, infield label disappears as expected. If you click on a reset button: <input type="reset" value="Reset"/> the infield label does not come back. I can manually .blur() the field, but there must be an easier way. I saw this previously closed issue: https://github.com/dcneiner/In-Field-Labels-jQuery-Plugin/issues/2 which mentions a refresh method, however I don't see that it has ever been implemented.

**Comment by dcneiner** [comment]
Sorry @webaholik, that refresh concept was in a branch I was working on back then that never got released. I think in its current state, you have to jump through some hoops.

You could use the `baseClass` option (In this example set to `infield_label`), then in response to a reset call the following code:

```js
// assuming you have a reference to your form
form.find( ".infield_label" ).each( function ( i, el ) {
   var infield = $( el ).data( "InFieldLabels" );
   infield.checkForEmpty();
});
```

That gets the reference to the InFieldLabel widget and tests for empty.

**Comment by webaholik** [comment]
This does partially work, but still has an issue...any thoughts on why it
only works after I press reset button a second time?

**Comment by dcneiner** [comment]
@webaholik My guess is you need to put it in a `setTimeout( ..., 0 )` so the browser has time to clear the fields before you run your reset code.

**Comment by webaholik** [comment]
You are correct (could have sworn I tried that, but thanks!). Also, worth
mentioning for future audience: passing true: infield.checkForEmpty(true);
is required to show opacity:1.0 otherwise it refreshes at 0.5.
